name: Deploy to cloudtype
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "1. Checkout"
        uses: actions/checkout@v2

      - name: "2. Connect deploy key"
        uses: cloudtype-github-actions/connect@v1
        with:
          token:  ${{ secrets.CLOUDTYPE_TOKEN }} 
          ghtoken:  ${{ secrets.GHP_TOKEN }} 
      
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token:  ${{ secrets.CLOUDTYPE_TOKEN }} 
          project: webinar01/react-app
          stage: main
          yaml: |
            name: react
            app: web
            options:
              docbase: /build
              nodeversion: 14
              spa: true
            context:
              git:
                url:  git@github.com:${{ github.repository }}.git 
                ref:  ${{ github.ref }} 
              preset: react

